import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import NextAuthProvider from "@/providers/NextAuthProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import BalanceProvider from "@/providers/BalanceProvider";
import UserProvider from "@/providers/UserProvider";
import ExpenseProvider from "@/providers/ExpenseProvider";
import BudgetProvider from "@/providers/BudgetProvider";
import CategoryProvider from "@/providers/CategoryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <NextAuthProvider>
          <ReactQueryProvider>
            <UserProvider>
              <ExpenseProvider>
                <BudgetProvider>
                  <BalanceProvider>
                    <CategoryProvider>
                    <ToastContainer />
                    {children}
                    </CategoryProvider>
                  </BalanceProvider>
                </BudgetProvider>
              </ExpenseProvider>
           
            </UserProvider>
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
